### ISSUE TITLE
2019 Tasks

### ISSUE THREAD

**Issue by jdorfman** [jdorfman/www#15]
**Part 1:**
- [x] Move off MaxCDN to GH Pages w/ Let's Encrypt (LE)
- [x] Switch to Jekyll
- [x] Update footer
- [x] Update `DOCUMENTATION.md`
- [x] Jekyll HTML minify - https://github.com/penibelst/jekyll-compress-html
---
**Part 2:**
- [x] Remove old blog posts
- [x] Remove old media
- [x] Liquid templating/yml for all media
- [x] Make a donation to LE
---
**Part 3:**
- [x] Favicon
---
Part 4:
- [x] OSCON

**Comment by jdorfman** [comment]
![image](https://user-images.githubusercontent.com/398230/50862273-19a3fe00-1350-11e9-9bc1-250d63315fac.png)
